
name: GitHub Tag Push Action

on:
 workflow_dispatch:
   inputs:
     tag_version:
       description: 'tag_version'
       required: true
       default: 'v0.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # with:
      #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      #   fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      #   ref: ${{ github.event.inputs.tag_version }}

    # - run: |
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    #     echo "${{ github.ref }}"
    #     echo "${{ github.sha }}"

    - name: Add tag
      run: |
        # git fetch --tags
        git tag "${{ github.event.inputs.tag_version }}"

    - name: Push changes
      uses: naofumi-fujii/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    - name: On success
      if: ${{ success() }}
      run: |
        echo success

    - name: On failure
      if: ${{ failure() }}
      run: |
        echo failure
