
name: Github Push Action

on:
 workflow_dispatch:
   inputs:
     tag_version:
       description: 'tag_version'
       required: true
       default: 'v0.0.0'
     # tags:
     #   description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    # - name: Create local changes
    #   run: |
    #     ...

    - name: add tag
      run: |
        # git config --local user.email "action@github.com"
        # git config --local user.name "GitHub Action"
        git fetch --tags
        # echo "Log level: ${{ github.event.inputs.logLevel }}"
        # echo "Tags: ${{ github.event.inputs.tags }}"
        git tag "${{ github.event.inputs.tag_version }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
